app/catalog/models.py
from app import db, login_manager

from datetime import datetime


# Publication table
class Publication(db.Model):
    __tablename__ = 'publication'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        return '{}'.format(self.name)


# BOOKS TABLE
class Book(db.Model):
    __tablename__ = 'book'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(500), nullable=False, index=True)
    author = db.Column(db.String(350))
    avg_rating = db.Column(db.Float)
    format = db.Column(db.String(50))
    image = db.Column(db.String(100), unique=True)
    num_pages = db.Column(db.Integer)
    pub_date = db.Column(db.DateTime, default=datetime.utcnow())

    # ESTABLISH RELATIONSHIP
    pub_id = db.Column(db.Integer, db.ForeignKey('publication.id'))

    def __init__(self, title, author, avg_rating, book_format, image, num_pages, pub_id):
        self.title = title
        self.author = author
        self.avg_rating = avg_rating
        self.format = book_format
        self.image = image
        self.num_pages = num_pages
        self.pub_id = pub_id

    def __repr__(self):
        return '{} by {}'.format(self.title, self.author)

app/catalog/forms.py
from flask_wtf import FlaskForm
from werkzeug.utils import secure_filename
from wtforms import StringField, SubmitField, IntegerField, FloatField, FileField
from wtforms.validators import DataRequired, ValidationError

from app.catalog.models import Publication, Book


class EditBookForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    format = StringField('Format', validators=[DataRequired()])
    num_pages = StringField('Pages', validators=[DataRequired()])
    submit = SubmitField('Update')

def image_exists(form,field):
    filename = secure_filename(form.img_file.data.filename)
    book = Book.query.filter_by(image=filename).first()

    if book:
        raise ValidationError('Image Already Exists')

def publisher_id_not_exist(form,field):
    id = Publication.query.filter_by(id=field.data).first()

    if not id:
        raise ValidationError('Publisher Doesnot exist Exists')
class CreateBookForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    author = StringField('Author', validators=[DataRequired()])
    avg_rating = FloatField('Rating', validators=[DataRequired()])
    format = StringField('Format', validators=[DataRequired()])

    img_file = FileField( validators=[DataRequired(), image_exists])
    num_pages = IntegerField('Pages', validators=[DataRequired()])
    pub_id = IntegerField('Publisher ID', validators=[DataRequired(),publisher_id_not_exist])
    submit = SubmitField('Create')

def publisher_exists(form,field):
    name = Publication.query.filter_by(name=field.data).first()

    if name:
        raise ValidationError('Publisher Already Exists')



class CreatePublisherForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), publisher_exists])
    id = IntegerField('Publisher ID', validators=[DataRequired()])
    submit = SubmitField('Create')

app/catalog/__init__.py
# app/catalog/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__, template_folder='templates')

from app.catalog import routes

app/catalog/routes.py
from flask_login import current_user, login_user, login_required
from werkzeug.utils import secure_filename

from app.auth.forms import LoginForm
from app.auth.models import User
from app.catalog import main
from app import db
from app.catalog.models import Book, Publication
from flask import render_template, flash, redirect, url_for, request
from app.catalog.forms import EditBookForm, CreateBookForm, CreatePublisherForm

ROWS_PER_PAGE = 6


# main -- blueprint
@main.route('/', methods=['GET', 'POST'])
def display_books():
    # Setting pagination configuration
    page = request.args.get('page', 1, type=int)

    books = Book.query.paginate(page=page, per_page=ROWS_PER_PAGE)  # Queries the database (calling class from models)
    return render_template('home.html', books=books)  # sending book object to Home.html file


@main.route('/display/publisher/<publisher_id>')
@login_required
def display_publisher(publisher_id):
    publisher = Publication.query.filter_by(id=publisher_id).first()
    publisher_books = Book.query.filter_by(pub_id=publisher.id).all()

    return render_template('publisher.html', publisher=publisher, publisher_books=publisher_books)


@main.route('/book/delete/<book_id>', methods=['GET', 'POST'])
@login_required
def delete_book(book_id):
    book = Book.query.get(book_id)
    if request.method == 'POST':
        db.session.delete(book)
        db.session.commit()
        flash('Book deleted successfully')

        return redirect(url_for('main.display_books'))
    return render_template('delete_book.html', book=book, book_id=book_id)


@main.route('/edit/book/<book_id>', methods=['GET', 'POST'])
@login_required
def edit_book(book_id):
    book = Book.query.get(book_id)
    form = EditBookForm(obj=book)
    if form.validate_on_submit():
        book.title = form.title.data
        book.format = form.format.data
        book.num_pages = form.num_pages.data
        db.session.add(book)
        db.session.commit()
        flash('Edited Successfully ')
        return redirect(url_for('main.display_books'))
    return render_template('edit_book.html', form=form)


@main.route('/create/book/<pub_id>', methods=['GET', 'POST'])
@login_required
def create_book(pub_id):
    form = CreateBookForm()
    # form.pub_id.data = pub_id #prepopulates the pub_id

    if form.validate_on_submit():
        filename = secure_filename(form.img_file.data.filename)
        form.img_file.data.save('app/static/img/' + filename)
        book = Book(title=form.title.data, author=form.author.data, avg_rating=form.avg_rating.data,
                    book_format=form.format.data,
                    image=filename, num_pages=form.num_pages.data, pub_id=form.pub_id.data)
        db.session.add(book)
        db.session.commit()
        flash('Book Added Successfully')

        return redirect(url_for('main.display_publisher', publisher_id=form.pub_id.data))
    return render_template('create_book.html', form=form, pub_id=form.pub_id.data)


@main.route('/create/publisher/', methods=['GET', 'POST'])
@login_required
def create_publisher():
    form = CreatePublisherForm()

    if form.validate_on_submit():
        publisher = Publication(name=form.name.data)
        db.session.add(publisher)
        db.session.commit()
        flash('Publisher Added Successfully')

        return redirect(url_for('main.display_publisher', publisher_id=form.id.data))
    return render_template('createpublisher.html', form=form)

app/catalog/templates/create_book.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
  <h4 style ="margin-left : 45px"> Create a new book</h4>
  <hr>
  {{form.hidden_tag()}}
    {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/catalog/templates/createpublisher.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
  <h4 style ="margin-left : 45px"> Add a New Publisher ?</h4>
  {{form.hidden_tag()}}
    {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/catalog/templates/delete_book.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
  <h4 style ="margin-left : 45px"> Delete the book ?</h4>
  <hr>
  <p style=" margin-left: 45px">
    Book Id : {{book.id}}<br>
    Title   : {{book.title}} <br>
    Author  :{{book.author}} <br>
  </p>
  <br>
  <form action="{{url_for('main.delete_book',book_id = book.id)}}" method="POST" style="margin-left:45px">
    <button type="submit" class="btn btn-sm btn-primary">Delete </button>

  </form>

</div>
{% endblock %}

app/catalog/templates/edit_book.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
  <h4 style ="margin-left : 45px"> Update this book ?</h4>
  {{form.hidden_tag()}}
    {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/catalog/templates/hello.html
<h1>Hello</h1>

app/catalog/templates/home.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container books">
        <div class="row">
            {% for book in books.items %}
            <div class="col-md-4">
                <img src ="static/img/{{book.image}}" alt="book-img" height="200" width="190" class="img-rounded">
                <h4>Title :{{book.title}}</h4>
                <p>Authors :{{book.author}}</p>
                <p>Format :{{book.format}}</p>
                <p>Rating :{{book.avg_rating}} </p>
                <p>Pages :{{book.num_pages}}</p>
                <p><a href="{{url_for('main.display_publisher', publisher_id = book.pub_id)}}">Publisher Id : {{book.pub_id}}</a> </p>
                <span class="label label-success"><a href="{{url_for('main.create_book',pub_id = book.pub_id)}}" style="color: floralwhite"> Add new book </a> </span>
                <span class="label label-primary"><a href="{{url_for('main.edit_book',book_id = book.id)}}" style="color: floralwhite"> Edit</a> </span>
                <span class="label label-info"><a href="{{url_for('main.delete_book',book_id = book.id)}}" style="color: floralwhite"> Delete</a> </span>

                <br>
            </div>
            {% endfor %}
        </div>
    </div>
<div class="text-right">
    <a href="{{ url_for('main.display_books', page=books.prev_num) }}"
       class="btn btn-outline-dark
       {% if books.page == 1 %}disabled{% endif %}">
        &laquo;
    </a>
<!-- Loop through the number of pages to display a link for each-->
    {% for page_num in books.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
<!-- Check for the active page and set the link to "Active"-->
            {% if books.page == page_num %}
            <a href="{{ url_for('main.display_books', page=page_num) }}"
               class="btn btn-dark">
                {{ page_num }}
            </a>
            {% else %}
            <a href="{{ url_for('main.display_books', page=page_num) }}"
               class="btn btn-outline-dark">
                {{ page_num }}
            </a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
    <a href="{{ url_for('main.display_books', page=books.next_num) }}"
       class="btn btn-outline-dark
       {% if books.page == books.pages %}disabled{% endif %}">
        &raquo;
    </a>
</div>
<p  class="text-right" style="padding-right:30px">
Showing page {{ books.page }} of {{ books.pages }}
</p>
{% endblock%}

app/catalog/templates/layout.html
{% import 'bootstrap/wtf.html' as wtf %}

<html lang="en">
{% block head %}
<head>
    <meta charset="UTF-8">
    <title>Books Inc</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" >
  <link href="https://fonts.googleapis.com/css2?family=Sansita&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{{url_for('static', filename ='css/style.css')}}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script>
    function delete_flash(flash){
        $(flash).parent().remove()
    }
</script>
</head>
{% endblock head %}
{% block body %}


    <body>
    <div class="wrapper">
        {# navigation bar #}
        {% block navbar %}
        <nav class="navbar navbar-inverse">
            <div class="container">
                <a class="navbar-brand" href="{{ url_for('main.display_books') }}">The Book Catalog</a>

                <ul class="nav navbar-nav pull-right nav-list">
                    <li><a href="{{url_for('main.display_books')}}"> Home </a></li>
                    <li><a href="{{url_for('authentication.register_user')}}"> Register </a></li>
                    <li>{% if  current_user.is_authenticated%}
                        <a href="{{url_for('authentication.log_out_user')}}"> Sign Out </a></li>

                    {% else %}
                    <a href="{{url_for('authentication.do_the_login')}}">SignIn</a>
                    {% endif%}
                    <li><a href="{{url_for('main.create_publisher')}}"> Add Publisher </a></li>
                     <li><a href="{{url_for('main.create_book',pub_id = 1)}}"> Add Book </a></li>
                    <li><a href="">
                        {%if current_user.is_authenticated%}
                        Logged In as <b style="color: deeppink">{{current_user.user_name.title()}}</b>
                        {% else%}
                        Not Logged In
                        {% endif%}
                    </a> </li>
                </ul>
            </div>
        </nav>
        {% endblock navbar %}
        {# flash messages#}
        {% for msg in get_flashed_messages()%}
             <div class="container alert alert-info">
                 <i class="close icon" onclick=delete_flash(this)>x</i>
                 {{msg}}
             </div>
        {% endfor %}
        {# empty block for custom content #}
        {% block content %}

        {% endblock content %}

        {# footer #}
        {% block footer %}
        <footer>
            <div class="container ftr">
                <hr>
                <p class="text-center small"> The Book Catalog &copy;	| 2022 </p>
            </div>
        </footer>
        {% endblock footer %}

    </div>
    </body>
    {% endblock body %}
</html>

app/catalog/templates/publisher.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container publisher">
        <h4> Books by {{publisher.name}}</h4>
        <hr>
        <br>
            <ol>
                {%for book in publisher_books %}
                  <li type="1">
                    {{book.title}} by {{book.author}}
                  </li>
                {% endfor %}
            </ol>
            </div>
{% endblock%}